### ISSUE TITLE
incompatibility with MSL.Fluid and hard to deal with initialization

### ISSUE THREAD

**Issue by Satinelamp** [ThermoSysPro/ThermoSysPro#1]
I just read the code and tried to use the library, but this library seems not incompatible with MSL.Fluid, which is because of the different definitions of connectors used. In ThermoSysPro, the connector doesn't use flow variables or stream variables.  I know that you use the current definitions for some reasons, but I still recommend to modify the connector to be compatible with MSL.

Regarding the initialization, I have to set initial values to some very low-level variables, and it is hard to locate the right ones I should use. I think the library is using some techniques to choose the variables, but I am not sure how, maybe there should be more explanation on this topic.

**Comment by ThermoSysPro** [comment]
The connectors are not intended to adapt to MSL for many technical reasons. For instance, the connectors will be modified in v4 so as to fusion static and dynamic model without singularities when the flow is null. This is incompatible with the MSL connectors.

We are working on data reconciliation to facilitate initialization in TSP.

**Comment by Satinelamp** [comment]
Is there a timeline of the development course? I plan to use ThermoSysPro as a training tool for my course in the next semester, but I find that the initialization issues could be hard to debug, especially for the rookie students.
